"""add table to save meta data to persist embedding status

Revision ID: 2452fe6262d7
Revises: b50193fc9f5c
Create Date: 2025-10-04 06:25:40.114811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2452fe6262d7'
down_revision: Union[str, Sequence[str], None] = 'b50193fc9f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'file_uploads',
        sa.Column('file_id', sa.UUID(), primary_key=True, nullable=False),
    sa.Column('user_id', sa.UUID(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('file_name', sa.String(), nullable=False),
        sa.Column('upload_time', sa.DateTime(), nullable=True),
        sa.Column('embedding_status', sa.String(), nullable=True),
        sa.Column('vector_count', sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, 'organizations', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS file_uploads CASCADE")    # ### end Alembic commands ###
